<?xml version="1.0"?>
<!--  
*****************************************************************************************
*
*  Filename:			  amr.xacro
*  Created:				  08/01/202$
*  Last Modified:	  08/01/2024
*  Author:				  Archit Jain
*  
*****************************************************************************************
-->

<robot name="amr" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find amr_description)/models/amr/amr.gazebo" />
  <xacro:include filename="$(find amr_description)/models/amr/materials.xacro" />

  <!-- ****************** BASIC INERTIAL MACROS ***************************  -->
  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${m}"/>
      <inertia  ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" 
                iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" 
                izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="cylinder_inertia" params="m r h *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${m}"/>
      <inertia  ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" 
                iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" 
                izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>
  <xacro:macro name="sphere_inertia" params="m r *origin">
    <inertial>
      <xacro:insert_block name="origin"/>
      <mass value="${m}"/>
      <inertia  ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" 
                iyy="${(2/5) * m * (r*r)}" iyz="0.0" 
                izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- ****************** ROBOT CONSTANTS *******************************  -->
  <!-- Define the size of the robot's main chassis in meters -->
  <xacro:property name="amr_base_width" value="0.30"/>
  <xacro:property name="amr_base_height" value="0.05"/>
  <xacro:property name="amr_base_length" value="0.40"/>
  <xacro:property name="amr_base_mass" value="1500"/>
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.015" />
  <xacro:property name="wheel_mass" value="150" />
  <xacro:property name="wheel_zoff" value="0.025"/>    <!-- Set wheel Z offset to 0 to align wheel axis to AMR base -->
  <xacro:property name="caster_wheel_mass" value="10" />
  <xacro:property name="lidar_radius" value="0.05" />
  <xacro:property name="lidar_height" value="0.04" />
  <xacro:property name="lidar_mass" value="100" />
  <xacro:property name="pi_2" value="1.5707963267949" />
  <!-- <xacro:property name="pi" value="3.141592654" /> -->

  <!-- ****************** ROBOT BASE FOOTPRINT ***************************  -->
  <!-- Define the center of the main robot chassis projected on the ground -->	
  <link name="base_footprint"/>

  <!-- The base footprint of the robot is located underneath the chassis -->
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0.0 0.0 ${(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

  <!-- ****************** ROBOT BASE LINK ***************************  -->
  <link name="base_link"/>

  <!-- The base link of the robot is located on the chassis -->
  <joint name="base_link_joint" type="fixed">
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="amr_base" />
  </joint>
  
  <!-- ********************** AMR BASE *********************************  -->
  <link name="amr_base">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${amr_base_length} ${amr_base_width} ${amr_base_height}"/>
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${amr_base_length} ${amr_base_width} ${amr_base_height}"/>
      </geometry>
    </collision>
    <xacro:box_inertia m="${amr_base_mass}" w="${amr_base_width}" d="${amr_base_length}" h="${amr_base_height}">
      <origin xyz="0 0 0" rpy="${pi_2} 0 ${pi_2}"/>
    </xacro:box_inertia>
  </link>

  <!-- ********************** AMR LEFT WHEEL JOINT *********************************  -->
  <joint name="amr_LW_joint" type="continuous">
      <parent link="amr_base"/>
      <child link="amr_LW"/>
      <origin xyz="0.0 ${-amr_base_width/2 - wheel_width/2} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
  </joint>

  <!-- ********************** AMR LEFT WHEEL *********************************  -->
  <link name="amr_LW">
    <visual>
      <origin xyz="0 0 0" rpy="${pi_2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi_2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}">
      <origin xyz="0 0 0" rpy="${pi_2} 0.0 0.0"/>
    </xacro:cylinder_inertia>
  </link>

  <!-- ********************** AMR RIGHT WHEEL JOINT *********************************  -->
  <joint name="amr_RW_joint" type="continuous">
      <parent link="amr_base"/>
      <child link="amr_RW"/>
      <origin xyz="0.0 ${amr_base_width/2 + wheel_width/2} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
  </joint>

  <!-- ********************** AMR RIGHT WHEEL *********************************  -->
  <link name="amr_RW">
    <visual>
      <origin xyz="0 0 0" rpy="${pi_2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi_2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_width}">
      <origin xyz="0 0 0" rpy="${pi_2} 0.0 0.0"/>
    </xacro:cylinder_inertia>
  </link>

  <!-- *********************** FRONT CASTER WHEEL JOINT ******************************  -->
  <joint name="back_caster_joint" type="fixed">
    <parent link="amr_base"/>
    <child link="front_caster"/>
    <origin xyz="${amr_base_length/3} 0.0 ${-(amr_base_height/2)}" rpy="0 0 0"/>
  </joint>

  <!-- *********************** FRONT CASTER WHEEL ******************************  -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(amr_base_height/2))}"/>
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(amr_base_height/2))}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${caster_wheel_mass}" r="${(wheel_radius+wheel_zoff-(amr_base_height/2))}">
      <origin xyz="0 0 0" rpy="${pi_2} 0 ${pi_2}"/>
    </xacro:sphere_inertia>
  </link>

  <!-- *********************** REAR CASTER WHEEL JOINT ******************************  -->
  <joint name="rear_caster_joint" type="fixed">
    <parent link="amr_base"/>
    <child link="rear_caster"/>
    <origin xyz="${-amr_base_length/3} 0.0 ${-(amr_base_height/2)}" rpy="0 0 0"/>
  </joint>

  <!-- *********************** REAR CASTER WHEEL ******************************  -->
  <link name="rear_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(amr_base_height/2))}"/>
      </geometry>
      <material name="white" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(amr_base_height/2))}"/>
      </geometry>
    </collision>
    <xacro:sphere_inertia m="${caster_wheel_mass}" r="${(wheel_radius+wheel_zoff-(amr_base_height/2))}">
      <origin xyz="0 0 0" rpy="${pi_2} 0 ${pi_2}"/>
    </xacro:sphere_inertia>
  </link>

  <!-- ****************************** LIDAR JOINT *****************************    -->
  <joint name="lidar_joint" type="fixed">
    <parent link="amr_base"/>
    <child link="lidar"/>
    <origin xyz="0 0 ${wheel_radius-wheel_zoff+(lidar_height/2)}" rpy="0 0 0"/>
  </joint>

  <!-- ****************************** LIDAR *****************************    -->
  <link name="lidar">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <material name="red" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
    </collision>
    <xacro:cylinder_inertia m="${lidar_mass}" r="${lidar_radius}" h="${lidar_height}">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:cylinder_inertia>
  </link>

</robot>
